version: "3.3"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: on-failure
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_JAEGER_ENDPOINT=jaeger:16686/api/traces
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - RPCGAME_MONGODB_URL=mongodb://root:qwerty12@mongo:27017/
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwerty12

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      RPCGAME_MONGODB_ADMINUSERNAME: root
      RPCGAME_MONGODB_ADMINPASSWORD: qwerty12
      RPCGAME_MONGODB_URL: mongodb://root:qwerty12@mongo:27017/